add timeout output

diff --git a/autograder/run_autograder b/autograder/run_autograder
--- a/autograder/run_autograder
+++ b/autograder/run_autograder
@@ -44,15 +44,24 @@ for try in $(seq 1 $MAXRETRYS); do
 	echo "Running grading script"
     timeout -v $TIMEOUT python3 grade.py
 
-    if [ $? -eq 0 ]; then
-        echo "Grading succeeded."
-		status=0
-        break
-    else
-        echo "Grading failed. Retrying..."
-		status=1
-        sleep 5
-    fi
+
+	case $? in
+		0)
+			echo "Grading succeeded."
+			status=0
+			break
+			;;
+		124)
+			echo "Timeout."
+			status=0
+			cp timeout.json /autograder/results/results.json
+			;;
+		*)
+			echo "Grading failed. Retrying..."
+			status=1
+			sleep 5
+			;;
+	esac
 done
 
 # If grading still didn't work after max trys
